// Generates the catalog mirror in ../lovable-skills/skills/jevify from this repository.
// The catalog workflow then syncs that folder to lucioamor/lovable-skill-jevify, whose README Lovable users read.
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const target = resolve(root, "..", "lovable-skills", "skills", "jevify");
const version = (await readFile(resolve(root, "VERSION.md"), "utf8")).match(/Current version: `(v\d+\.\d+\.\d+)`/)?.[1];
if (!version) throw new Error("VERSION.md has no `Current version: vX.Y.Z` line");

await mkdir(target, { recursive: true });
await copyFile(resolve(root, "skills", "jevify", "SKILL.md"), resolve(target, "SKILL.md"));
await copyFile(resolve(root, "VERSION.md"), resolve(target, "VERSION.md"));
await copyFile(resolve(root, "LICENSE"), resolve(target, "LICENSE"));
await writeFile(
  resolve(target, "README.md"),
  `# jevify — /jevify and /jevify migrate for Lovable

\`/jevify\` audits the runtime AI calls in a Lovable project (Edge Functions and AI gateway calls included), separates generation from structured decisions, and proposes JEV candidates in a report returned in chat. It never edits code. \`/jevify migrate <finding>\` moves one approved candidate to JEV behind an \`off | shadow | on\` flag, starting in shadow mode and keeping the existing AI path.

It targets the deployed app's runtime AI usage, not Lovable build credits. Effects are hypotheses until measured in shadow mode.

## Import into Lovable

**Settings → Skills → Add → Import from GitHub**, then paste:

\`\`\`text
https://github.com/lucioamor/lovable-skill-jevify
\`\`\`

Run \`/jevify\` inside a project. Re-import to update.

## Optional: jevify MCP connector

**Connectors → custom MCP server** with \`https://jevify.lovable.app/mcp\`, then sign in. The skill asks before sending files and never sends \`.env\` files or credentials. Without the connector, no code is sent to the jevify service.

## Source and version

- Version: \`${version}\`
- Canonical source (edit here only): [lucioamor/jevify](https://github.com/lucioamor/jevify) — \`skills/jevify/SKILL.md\`
- This folder is generated by \`scripts/export-lovable.mjs\` in that repository. Do not edit it by hand.

Created by Lucio Amorim. Licensed under CC BY 4.0.
`,
  "utf8",
);
console.log(`Exported jevify ${version} to ${target}`);
